### ISSUE TITLE
There shouldn't be an angle bracket in such cases

### ISSUE THREAD

**Issue by nomardt** [nomardt/OpenAI-Search#24] opened 2023-01-30 10:10 UTC
![Screenshot at 2023-01-30 13-06-46](https://user-images.githubusercontent.com/115152912/215448406-19e58c29-f0b9-4678-bf14-f8a948074d1e.png)

**Comment by LagrangeH** [comment] 2023-01-30 14:09
duplicate of #28

**Closed as not planned by LagrangeH** 2023-01-30 14:09 UTC
Labels: duplicate, enhancement
